services:
  - type: web
    name: saigon-soundscape
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: B2_ENDPOINT
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: B2_APPLICATION_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_REGION
        sync: false
      - key: MONGO_URI
        sync: false
